### ISSUE TITLE
ngFor in message Tag

### ISSUE THREAD

**Issue by joehansen** [mattlewis92/angular2-bootstrap-confirm#24]
Hello, 

thanks for the great component :-)

Is it possible to use ngFor Directive in the message Tag? 

<popover message='<div ngFor let item of items; let i = index; >..</div>'
or
<popover message='<div *ngFor="let vertrag of items">..</div>'

won`t work. 

Thanks.

**Comment by mattlewis92** [comment]
I'm afraid this isn't possible due to the way angular works (user input creating an angular template would be an [security nightmare](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#content-security)). The message option only allows simple html tags. You might want to try using a custom template instead: https://github.com/mattlewis92/angular2-bootstrap-confirm/blob/master/test/angular2-bootstrap-confirm.spec.ts#L385-L422
